name: release

on:
  push:
    tags:
      - "v[0-9].[0-9]+.[0-9]+" # e.g. v1.0.0

env:
  SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}

jobs:
  release-android:
    runs-on: ubuntu-latest

    name: ðŸ¤– Release Android

    steps:
      - name: ðŸ“š Git Checkout
        uses: actions/checkout@v4

      - name: ðŸ“‚ Git Fetch Tags
        run: git fetch --tags

      - name: â˜•ï¸ Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: ðŸ¦ Setup Shorebird
        uses: shorebirdtech/setup-shorebird@latest
        with:
          cache: true

      - name: ðŸ” Decode Keystore
        run: echo ${{ secrets.KEYSTORE }} | base64 --decode > ${{ github.workspace }}/keystore.jks

      - name: ðŸ§¹ Clean Flutter Build
        run: flutter clean

      - name: ðŸš€ Build APK
        run: flutter build apk --release

      - name: ðŸš€ Shorebird Release
        uses: shorebirdtech/shorebird-release@latest
        env:
          KEYSTORE_FILE: ${{ github.workspace }}/keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
        with:
          platform: android
          args: "--verbose --artifact=apk"

      - name: ðŸ“¦ Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flutter_and_friends-${{ github.ref_name }}.apk
          path: build/app/outputs/apk/release/app-release.apk

      - name: ðŸ“¦ Upload App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: QUIZ-${{ github.ref_name }}.aab
          path: build/app/outputs/bundle/release/app-release.aab
